server:
  port: 9006

spring:
    application:
      name: stock-api
    data:
      mongodb:
        username: stock
        password: Stock@123
        uri: mongodb://localhost:27017/stock
        
env: dev
